describe('Validações simulado de credito', () => {

  beforeEach(() => {
    cy.visit('https://www.serasa.com.br/ecred/simulador/')
    cy.wait(1000)
  })

  it('Validar simulação de emprestimo no valor de R$ 1.000,00 em 6X', () => {
    cy.get('#slider-range[type=range]').click()
      .as ('range')
      .invoke('val', 1000)
      .should('have.value', 1000)
      .trigger('change')
    cy.get('#slider-range-month[type=range]').click()
      .as ('range')
      .invoke('val', 6)
      .should('have.value', 6)
      .trigger('change')
    // cy.get('#amount')
    // .should('contain', 'R$ 1.000,00')
    // cy.get('#month-amount')
    //   .should('contain', '6 meses')
    // cy.get('#month-amount-output')
    // .should('contain', '6x')
    // cy.get('#price-number')
    // .should('contain', '271,27')
  })

  // it('Validar simulação emprestimo no valor de R$ 4.000,00 em 12X', () => {
  //   cy.get('#slider-range[type=range]')
  //     .as ('range')
  //     .click()
  //     .invoke('val', 4000)
  //     .should('have.value', 4000)
  //     .trigger('change')
  //   cy.get('#slider-range-month[type=range]')
  //     .as ('range').click()
  //     .invoke('val', 12)
  //     .should('have.value', 12)
  //     .trigger('change')
  //   cy.get('#amount')
  //   .should('contain', 'R$ 4.000,00')
  //   cy.get('#month-amount')
  //     .should('contain', '12 meses')
  //   cy.get('#month-amount-output')
  //   .should('contain', '12x')
  //   cy.get('#price-number')
  //   .should('contain', '478,49')
  // })

  // it('Validar simulação de emprestimo no valor de R$ 6.000,00 em 24X', () => {
  //   cy.get('#slider-range[type=range]')
  //     .as ('range')
  //     .click()
  //     .invoke('val', 6000)
  //     .should('have.value', 6000)
  //     .trigger('change')
  //   cy.get('#slider-range-month[type=range]')
  //     .as ('range').click()
  //     .invoke('val', 24)
  //     .should('have.value', 24)
  //     .trigger('change')
  //   cy.get('#amount')
  //   .should('contain', 'R$ 6.000,00')
  //   cy.get('#month-amount')
  //     .should('contain', '24 meses')
  //   cy.get('#month-amount-output')
  //   .should('contain', '24x')
  //   cy.get('#price-number')
  //   .should('contain', '347,89')
  // })

})
